* nextcloud image does not install itself * config script now works fine * adding nextcloud client for further tests

diff --git a/nextcloud/config/setup b/nextcloud/config/setup
--- a/nextcloud/config/setup
+++ b/nextcloud/config/setup
@@ -1,4 +1,21 @@
 #!/bin/bash
+# exit when any command fails
+set -e
+
+exit_on_error() {
+    exit_code=$1
+    last_command=${@:2}
+    if [ $exit_code -ne 0 ]; then
+        >&2 echo "\"${last_command}\" command failed with exit code ${exit_code}."
+        exit $exit_code
+    fi
+}
+
+# keep track of the last executed command
+trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
+# echo an error message before exiting
+trap 'exit_on_error $? $last_command' EXIT
+
 function occ {
 	cmd="php /var/www/html/occ $@"
 	su www-data -s /bin/bash -c "$cmd"
@@ -8,22 +25,22 @@ apt-get update
 apt-get install -y jq wait-for-it
 chown www-data /var/www/html/data
 wait-for-it -t 0 db:3306
-sleep 2
 
-now=`date +%s`
 source /secrets/compose
-occ maintenance:install --database="mysql" --database-name="nextcloud" --database-host="db" --database-user="nextcloud" --database-pass="${MYSQL_PASSWORD}" --database-table-prefix="" --admin-user="admin$now" --admin-pass="${NEXTCLOUD_ADMIN_PASSWORD}"
-export OC_PASS="${NEXTCLOUD_ADMIN_PASSWORD}"
-occ user:add --password-from-env --display-name="admin" --group="admin" admin
-occ user:delete "admin$now"
+
+echo install nextcloud
+occ maintenance:install --database="mysql" --database-name="nextcloud" --database-host="db" --database-user="nextcloud" --database-pass="${MYSQL_PASSWORD}" --database-table-prefix="" --admin-user="admin" --admin-pass="${NEXTCLOUD_ADMIN_PASSWORD}"
 
 occ config:system:set trusted_domains 1 --value="coruscant"
 occ config:system:set trusted_domains 2 --value="niobe"
+occ config:system:set trusted_domains 3 --value="localhost"
 
 #occ config:system:set overwrite.cli.url --value="https://nextcloud.my.domain"
-occ config:system:set memcache.local --value="\OC\Memcache\APCu" --type=string
+#TODO activate again
+#occ config:system:set memcache.local --value="\OC\Memcache\APCu" --type=string
 #occ config:system:set defaultapp --value="calendar" --type=string
-occ config:system:set trashbin_retention_obligation --value="auto, 7" --type=string
+#TODO was not working
+#occ config:system:set trashbin_retention_obligation --value="auto, 7" --type=string
 #occ config:system:set log_rotate_size --value="10485760" --type=integer
 occ config:system:set logtimezone --value="Europe/Berlin" --type=string
 #occ config:system:set remember_login_cookie_lifetime --value="86400" --type=integer
@@ -47,6 +64,7 @@ occ config:app:set files_sharing outgoing_server2server_share_enabled --value="n
 occ config:app:set files_sharing lookupServerUploadEnabled --value="no"
 occ config:app:set core umgmt_send_email --value="true"
 
+occ group:add users
 # adding users if they do not exist
 COUNT=`cat /secrets/users | jq '.users|length'`
 for ((i=0;i<COUNT;i++)); do
